###
# curl -X POST http://localhost:8080/api/urls
#  -H "Content-Type: application/json"
#  -d '{"long_url": "https://www.google.com"}'
POST http://localhost:8085/api/urls
Content-Type: application/json

{
  "long_url": "https://www.google.com"
}

###

GET http://localhost:8085/002DEBy